import json
from pathlib import Path


OUT_JSON = Path(r"C:\Projects\SmartQuiz\src\components\data\comptiaSecurity701Questions.json")


QUESTIONS = [
    ("module_1", 1, "General Security Concepts", "Conceptos generales de seguridad",
     "Which principle ensures that only authorized users can view sensitive data?",
     "¿Qué principio asegura que solo usuarios autorizados puedan ver datos sensibles?",
     ["Confidentiality", "Availability", "Non-repudiation", "Resilience"],
     ["Confidencialidad", "Disponibilidad", "No repudio", "Resiliencia"], 0,
     "Confidentiality limits access to information so only authorized subjects can view it.",
     "La confidencialidad limita el acceso para que solo sujetos autorizados puedan ver la informacion."),
    ("module_1", 1, "General Security Concepts", "Conceptos generales de seguridad",
     "A system uses hashes to detect whether a file changed. Which CIA principle is being supported?",
     "Un sistema usa hashes para detectar si un archivo cambio. ¿Qué principio de la triada CIA se apoya?",
     ["Integrity", "Availability", "Confidentiality", "Obfuscation"],
     ["Integridad", "Disponibilidad", "Confidencialidad", "Ofuscacion"], 0,
     "Hashes help verify that data has not been modified.",
     "Los hashes ayudan a verificar que los datos no fueron modificados."),
    ("module_1", 1, "General Security Concepts", "Conceptos generales de seguridad",
     "Which control type is a security awareness policy?",
     "¿Qué tipo de control es una politica de concientizacion de seguridad?",
     ["Managerial", "Physical", "Technical", "Compensating"],
     ["Gerencial", "Fisico", "Tecnico", "Compensatorio"], 0,
     "Policies and risk governance are managerial controls.",
     "Las politicas y la gobernanza de riesgos son controles gerenciales."),
    ("module_1", 1, "General Security Concepts", "Conceptos generales de seguridad",
     "A camera records activity after business hours. Which control function is this?",
     "Una camara registra actividad fuera del horario laboral. ¿Qué funcion de control cumple?",
     ["Detective", "Corrective", "Directive", "Preventive"],
     ["Detectiva", "Correctiva", "Directiva", "Preventiva"], 0,
     "Detective controls identify or record suspicious activity.",
     "Los controles detectivos identifican o registran actividad sospechosa."),
    ("module_1", 1, "General Security Concepts", "Conceptos generales de seguridad",
     "What does non-repudiation provide?",
     "¿Qué proporciona el no repudio?",
     ["Proof that an action cannot reasonably be denied", "Guaranteed system uptime", "Anonymous communication", "Automatic malware removal"],
     ["Prueba de que una accion no puede negarse razonablemente", "Disponibilidad garantizada", "Comunicacion anonima", "Eliminacion automatica de malware"], 0,
     "Digital signatures and logs can support non-repudiation.",
     "Las firmas digitales y registros pueden apoyar el no repudio."),
    ("module_1", 2, "Threats, Vulnerabilities, and Mitigations", "Amenazas, vulnerabilidades y mitigaciones",
     "A user receives a targeted email that appears to come from their manager. What attack is most likely?",
     "Un usuario recibe un correo dirigido que parece venir de su gerente. ¿Qué ataque es mas probable?",
     ["Spear phishing", "Bluejacking", "SQL injection", "Directory traversal"],
     ["Spear phishing", "Bluejacking", "Inyeccion SQL", "Directory traversal"], 0,
     "Spear phishing is a targeted phishing attempt against a specific person or group.",
     "Spear phishing es un intento dirigido contra una persona o grupo especifico."),
    ("module_1", 2, "Threats, Vulnerabilities, and Mitigations", "Amenazas, vulnerabilidades y mitigaciones",
     "Which attack poisons a local mapping table to intercept traffic on a LAN?",
     "¿Qué ataque envenena una tabla local de mapeo para interceptar trafico en una LAN?",
     ["ARP spoofing", "DNSSEC", "Typosquatting", "Password spraying"],
     ["Suplantacion ARP", "DNSSEC", "Typosquatting", "Password spraying"], 0,
     "ARP spoofing can redirect traffic through the attacker on a local network.",
     "La suplantacion ARP puede redirigir trafico a traves del atacante en una red local."),
    ("module_1", 2, "Threats, Vulnerabilities, and Mitigations", "Amenazas, vulnerabilidades y mitigaciones",
     "Which vulnerability is most directly reduced by parameterized queries?",
     "¿Qué vulnerabilidad se reduce mas directamente con consultas parametrizadas?",
     ["SQL injection", "Replay attack", "Evil twin", "Rootkit"],
     ["Inyeccion SQL", "Ataque de repeticion", "Evil twin", "Rootkit"], 0,
     "Parameterized queries separate code from user input.",
     "Las consultas parametrizadas separan el codigo de la entrada del usuario."),
    ("module_1", 2, "Threats, Vulnerabilities, and Mitigations", "Amenazas, vulnerabilidades y mitigaciones",
     "A login page allows unlimited attempts against one account. Which attack is most likely?",
     "Una pagina de inicio de sesion permite intentos ilimitados contra una cuenta. ¿Qué ataque es mas probable?",
     ["Brute force", "Watering hole", "Cross-site scripting", "Race condition"],
     ["Fuerza bruta", "Watering hole", "Cross-site scripting", "Condicion de carrera"], 0,
     "Brute-force attacks repeatedly try credentials until one works.",
     "Los ataques de fuerza bruta prueban credenciales repetidamente hasta acertar."),
    ("module_1", 2, "Threats, Vulnerabilities, and Mitigations", "Amenazas, vulnerabilidades y mitigaciones",
     "Which mitigation best reduces credential stuffing risk?",
     "¿Qué mitigacion reduce mejor el riesgo de credential stuffing?",
     ["Multi-factor authentication", "Longer DHCP leases", "Open guest Wi-Fi", "Disabling logs"],
     ["Autenticacion multifactor", "Concesiones DHCP mas largas", "Wi-Fi de invitado abierto", "Deshabilitar registros"], 0,
     "MFA reduces the usefulness of stolen reused passwords.",
     "MFA reduce la utilidad de contrasenas reutilizadas robadas."),
    ("module_1", 2, "Threats, Vulnerabilities, and Mitigations", "Amenazas, vulnerabilidades y mitigaciones",
     "What is the best first action when ransomware is suspected on a workstation?",
     "¿Cuál es la mejor primera accion cuando se sospecha ransomware en una estacion de trabajo?",
     ["Isolate the device from the network", "Pay the ransom", "Disable backups", "Delete all logs"],
     ["Aislar el dispositivo de la red", "Pagar el rescate", "Deshabilitar respaldos", "Eliminar todos los logs"], 0,
     "Isolation helps contain spread while preserving evidence.",
     "El aislamiento ayuda a contener la propagacion y preservar evidencia."),
    ("module_1", 2, "Threats, Vulnerabilities, and Mitigations", "Amenazas, vulnerabilidades y mitigaciones",
     "Which malware hides at a low system level to maintain stealthy access?",
     "¿Qué malware se oculta a bajo nivel del sistema para mantener acceso sigiloso?",
     ["Rootkit", "Adware", "Logic bomb", "Key escrow"],
     ["Rootkit", "Adware", "Bomba logica", "Custodia de claves"], 0,
     "Rootkits are designed to hide and maintain privileged access.",
     "Los rootkits se diseñan para ocultarse y mantener acceso privilegiado."),
    ("module_1", 3, "Identity and Access", "Identidad y acceso",
     "Which access model grants permissions based on job function?",
     "¿Qué modelo de acceso otorga permisos segun la funcion laboral?",
     ["RBAC", "DAC", "MAC", "PAP"],
     ["RBAC", "DAC", "MAC", "PAP"], 0,
     "Role-based access control maps access to roles.",
     "El control de acceso basado en roles asigna permisos a roles."),
    ("module_1", 3, "Identity and Access", "Identidad y acceso",
     "What does the principle of least privilege require?",
     "¿Qué requiere el principio de minimo privilegio?",
     ["Users receive only the access needed for their tasks", "All users are administrators", "Passwords never expire", "Data is public by default"],
     ["Usuarios reciben solo el acceso necesario para sus tareas", "Todos son administradores", "Las contrasenas nunca expiran", "Los datos son publicos por defecto"], 0,
     "Least privilege limits unnecessary access and reduces impact.",
     "El minimo privilegio limita acceso innecesario y reduce impacto."),
    ("module_1", 3, "Identity and Access", "Identidad y acceso",
     "Which factor is something you are?",
     "¿Qué factor es algo que eres?",
     ["Fingerprint", "Password", "Smart card", "One-time code"],
     ["Huella digital", "Contrasena", "Tarjeta inteligente", "Codigo de un solo uso"], 0,
     "Biometrics are inherence factors.",
     "La biometria es un factor de inherencia."),
    ("module_2", 4, "Security Architecture", "Arquitectura de seguridad",
     "Why would an organization place public web servers in a DMZ?",
     "¿Por qué una organizacion colocaria servidores web publicos en una DMZ?",
     ["To isolate public services from the internal network", "To remove the need for firewalls", "To store private keys publicly", "To disable monitoring"],
     ["Para aislar servicios publicos de la red interna", "Para eliminar la necesidad de firewalls", "Para publicar claves privadas", "Para deshabilitar monitoreo"], 0,
     "A DMZ limits exposure between public services and internal assets.",
     "Una DMZ limita la exposicion entre servicios publicos y activos internos."),
    ("module_2", 4, "Security Architecture", "Arquitectura de seguridad",
     "What is a primary goal of network segmentation?",
     "¿Cuál es el objetivo principal de la segmentacion de red?",
     ["Limit the impact of a compromise", "Increase password length", "Replace encryption", "Remove authentication"],
     ["Limitar el impacto de un compromiso", "Aumentar longitud de contrasenas", "Reemplazar cifrado", "Eliminar autenticacion"], 0,
     "Segmentation constrains lateral movement.",
     "La segmentacion limita el movimiento lateral."),
    ("module_2", 4, "Security Architecture", "Arquitectura de seguridad",
     "Which cloud model places most infrastructure responsibility on the provider?",
     "¿Qué modelo de nube coloca la mayor responsabilidad de infraestructura en el proveedor?",
     ["SaaS", "IaaS", "On-premises", "Colocation"],
     ["SaaS", "IaaS", "Local/on-premises", "Colocation"], 0,
     "In SaaS, the provider manages the application platform and much of the stack.",
     "En SaaS, el proveedor administra la aplicacion y gran parte de la pila."),
    ("module_2", 4, "Security Architecture", "Arquitectura de seguridad",
     "Which technology centrally controls network behavior through software?",
     "¿Qué tecnologia controla centralmente el comportamiento de red mediante software?",
     ["SDN", "NAT", "RAID", "TPM"],
     ["SDN", "NAT", "RAID", "TPM"], 0,
     "Software-defined networking separates control from forwarding.",
     "SDN separa el control del reenvio de trafico."),
    ("module_2", 5, "Cryptography and PKI", "Criptografia y PKI",
     "Which control protects data at rest if a laptop is lost?",
     "¿Qué control protege datos en reposo si se pierde una laptop?",
     ["Full-disk encryption", "DNS filtering", "Load balancing", "Port mirroring"],
     ["Cifrado de disco completo", "Filtrado DNS", "Balanceo de carga", "Port mirroring"], 0,
     "Full-disk encryption protects stored data on the device.",
     "El cifrado de disco completo protege datos almacenados en el dispositivo."),
    ("module_2", 5, "Cryptography and PKI", "Criptografia y PKI",
     "What does a digital certificate primarily bind?",
     "¿Qué vincula principalmente un certificado digital?",
     ["An identity to a public key", "A password to a hash", "A VLAN to a subnet", "A log to a SIEM"],
     ["Una identidad a una clave publica", "Una contrasena a un hash", "Una VLAN a una subred", "Un log a un SIEM"], 0,
     "Certificates help prove that a public key belongs to an identity.",
     "Los certificados ayudan a probar que una clave publica pertenece a una identidad."),
    ("module_2", 5, "Cryptography and PKI", "Criptografia y PKI",
     "Which protocol is most appropriate for securing web traffic?",
     "¿Qué protocolo es mas apropiado para asegurar trafico web?",
     ["TLS", "Telnet", "SNMPv1", "FTP"],
     ["TLS", "Telnet", "SNMPv1", "FTP"], 0,
     "TLS encrypts and authenticates web sessions when used with HTTPS.",
     "TLS cifra y autentica sesiones web cuando se usa con HTTPS."),
    ("module_2", 5, "Cryptography and PKI", "Criptografia y PKI",
     "Which list identifies certificates that should no longer be trusted?",
     "¿Qué lista identifica certificados que ya no deben ser confiables?",
     ["CRL", "ACL", "NAT", "MTBF"],
     ["CRL", "ACL", "NAT", "MTBF"], 0,
     "A certificate revocation list identifies revoked certificates.",
     "Una lista de revocacion de certificados identifica certificados revocados."),
    ("module_2", 6, "Security Operations", "Operaciones de seguridad",
     "Which tool aggregates events from many systems for correlation and alerting?",
     "¿Qué herramienta agrega eventos de muchos sistemas para correlacion y alertas?",
     ["SIEM", "TPM", "HSM", "NAC"],
     ["SIEM", "TPM", "HSM", "NAC"], 0,
     "A SIEM collects and correlates logs for security monitoring.",
     "Un SIEM recopila y correlaciona logs para monitoreo de seguridad."),
    ("module_2", 6, "Security Operations", "Operaciones de seguridad",
     "What is the purpose of EDR?",
     "¿Cuál es el proposito de EDR?",
     ["Detect and respond to endpoint threats", "Replace backups", "Create VLANs", "Issue certificates"],
     ["Detectar y responder a amenazas en endpoints", "Reemplazar respaldos", "Crear VLANs", "Emitir certificados"], 0,
     "Endpoint detection and response monitors endpoint activity and supports response.",
     "EDR monitorea actividad en endpoints y apoya la respuesta."),
    ("module_2", 6, "Security Operations", "Operaciones de seguridad",
     "Which process restores systems after a tested outage scenario?",
     "¿Qué proceso restaura sistemas despues de un escenario probado de interrupcion?",
     ["Disaster recovery", "Reconnaissance", "Tokenization", "Data masking"],
     ["Recuperacion ante desastres", "Reconocimiento", "Tokenizacion", "Enmascaramiento de datos"], 0,
     "Disaster recovery focuses on restoring systems and data after disruption.",
     "La recuperacion ante desastres restaura sistemas y datos tras una interrupcion."),
    ("module_2", 6, "Security Operations", "Operaciones de seguridad",
     "Which activity should happen before applying patches broadly?",
     "¿Qué actividad debe ocurrir antes de aplicar parches ampliamente?",
     ["Test patches in a controlled environment", "Disable monitoring", "Delete rollback plans", "Share admin passwords"],
     ["Probar parches en un entorno controlado", "Deshabilitar monitoreo", "Eliminar planes de reversa", "Compartir contrasenas admin"], 0,
     "Testing reduces the chance of breaking production systems.",
     "Las pruebas reducen el riesgo de afectar sistemas de produccion."),
    ("module_3", 7, "Security Program Management", "Gestion del programa de seguridad",
     "What is the purpose of a risk register?",
     "¿Cuál es el proposito de un registro de riesgos?",
     ["Track identified risks, owners, likelihood, impact, and treatment", "Store encryption keys", "Replace incident reports", "List public IP addresses only"],
     ["Rastrear riesgos, duenos, probabilidad, impacto y tratamiento", "Guardar claves de cifrado", "Reemplazar reportes de incidentes", "Listar solo IPs publicas"], 0,
     "A risk register supports governance and risk tracking.",
     "Un registro de riesgos apoya la gobernanza y el seguimiento de riesgos."),
    ("module_3", 7, "Security Program Management", "Gestion del programa de seguridad",
     "Which risk response accepts the risk without additional controls?",
     "¿Qué respuesta al riesgo acepta el riesgo sin controles adicionales?",
     ["Acceptance", "Transfer", "Mitigation", "Avoidance"],
     ["Aceptacion", "Transferencia", "Mitigacion", "Evitacion"], 0,
     "Acceptance means leadership chooses to live with the risk.",
     "Aceptacion significa que la direccion decide convivir con el riesgo."),
    ("module_3", 7, "Security Program Management", "Gestion del programa de seguridad",
     "Which document defines expected employee technology behavior?",
     "¿Qué documento define el comportamiento esperado de empleados con tecnologia?",
     ["Acceptable use policy", "Certificate signing request", "Network packet capture", "Hash digest"],
     ["Politica de uso aceptable", "Solicitud de firma de certificado", "Captura de paquetes", "Resumen hash"], 0,
     "An acceptable use policy sets rules for proper technology use.",
     "Una politica de uso aceptable establece reglas para uso correcto de tecnologia."),
    ("module_3", 7, "Security Program Management", "Gestion del programa de seguridad",
     "Which metric estimates expected yearly financial loss from a risk?",
     "¿Qué metrica estima la perdida financiera anual esperada de un riesgo?",
     ["ALE", "RTO", "MTTR", "RPO"],
     ["ALE", "RTO", "MTTR", "RPO"], 0,
     "Annualized loss expectancy estimates yearly loss.",
     "La expectativa de perdida anual estima la perdida anual."),
    ("module_3", 8, "Governance, Risk, and Compliance", "Gobernanza, riesgo y cumplimiento",
     "Which regulation is most associated with payment card data?",
     "¿Qué regulacion se asocia mas con datos de tarjetas de pago?",
     ["PCI DSS", "HIPAA", "SOX", "FERPA"],
     ["PCI DSS", "HIPAA", "SOX", "FERPA"], 0,
     "PCI DSS focuses on protecting cardholder data.",
     "PCI DSS se enfoca en proteger datos de titulares de tarjetas."),
    ("module_3", 8, "Governance, Risk, and Compliance", "Gobernanza, riesgo y cumplimiento",
     "Which regulation is most associated with protected health information in the United States?",
     "¿Qué regulacion se asocia mas con informacion de salud protegida en Estados Unidos?",
     ["HIPAA", "PCI DSS", "GDPR", "FISMA"],
     ["HIPAA", "PCI DSS", "GDPR", "FISMA"], 0,
     "HIPAA applies to protected health information in covered healthcare contexts.",
     "HIPAA aplica a informacion de salud protegida en contextos de salud cubiertos."),
    ("module_3", 8, "Governance, Risk, and Compliance", "Gobernanza, riesgo y cumplimiento",
     "What is data minimization?",
     "¿Qué es la minimizacion de datos?",
     ["Collecting only data needed for a stated purpose", "Keeping all data forever", "Publishing logs publicly", "Removing encryption"],
     ["Recolectar solo datos necesarios para un proposito definido", "Guardar todos los datos para siempre", "Publicar logs", "Eliminar cifrado"], 0,
     "Data minimization reduces privacy and breach impact.",
     "La minimizacion reduce impacto de privacidad y brechas."),
    ("module_3", 8, "Governance, Risk, and Compliance", "Gobernanza, riesgo y cumplimiento",
     "Which assessment identifies gaps between current controls and desired requirements?",
     "¿Qué evaluacion identifica brechas entre controles actuales y requisitos deseados?",
     ["Gap analysis", "Packet capture", "Credential stuffing", "Token replay"],
     ["Analisis de brechas", "Captura de paquetes", "Credential stuffing", "Repeticion de token"], 0,
     "Gap analysis compares current and target states.",
     "El analisis de brechas compara estado actual y objetivo."),
    ("module_3", 8, "Governance, Risk, and Compliance", "Gobernanza, riesgo y cumplimiento",
     "Which practice helps prove that evidence was not tampered with?",
     "¿Qué practica ayuda a probar que la evidencia no fue manipulada?",
     ["Chain of custody", "Load balancing", "NAT overload", "Bluejacking"],
     ["Cadena de custodia", "Balanceo de carga", "NAT overload", "Bluejacking"], 0,
     "Chain of custody documents evidence handling from collection to presentation.",
     "La cadena de custodia documenta el manejo de evidencia desde recoleccion hasta presentacion."),
    ("module_3", 9, "Security Awareness", "Concientizacion de seguridad",
     "Which training topic helps users identify suspicious emails?",
     "¿Qué tema de entrenamiento ayuda a identificar correos sospechosos?",
     ["Phishing awareness", "Subnetting only", "RAID levels", "Printer calibration"],
     ["Concientizacion sobre phishing", "Solo subnetting", "Niveles RAID", "Calibracion de impresora"], 0,
     "Phishing awareness teaches users to identify and report suspicious messages.",
     "La concientizacion sobre phishing ensena a identificar y reportar mensajes sospechosos."),
    ("module_3", 9, "Security Awareness", "Concientizacion de seguridad",
     "Which behavior is a possible insider threat indicator?",
     "¿Qué comportamiento puede indicar una amenaza interna?",
     ["Accessing unusual amounts of data outside normal duties", "Using approved MFA", "Reporting phishing", "Locking a screen"],
     ["Acceder a cantidades inusuales de datos fuera de sus funciones", "Usar MFA aprobado", "Reportar phishing", "Bloquear pantalla"], 0,
     "Unusual access patterns can indicate insider risk.",
     "Patrones inusuales de acceso pueden indicar riesgo interno."),
    ("module_3", 9, "Security Awareness", "Concientizacion de seguridad",
     "What should users do with an unexpected USB drive found in a parking lot?",
     "¿Qué deben hacer los usuarios con una USB inesperada encontrada en un estacionamiento?",
     ["Report it according to policy", "Plug it in to identify the owner", "Copy files from it", "Disable antivirus first"],
     ["Reportarla segun la politica", "Conectarla para identificar al dueno", "Copiar sus archivos", "Deshabilitar antivirus primero"], 0,
     "Unknown removable media can carry malware and should be handled by policy.",
     "Medios removibles desconocidos pueden traer malware y deben manejarse segun politica."),
    ("module_1", 2, "Threats, Vulnerabilities, and Mitigations", "Amenazas, vulnerabilidades y mitigaciones",
     "Which attack tricks users by creating a malicious wireless access point that resembles a legitimate one?",
     "¿Qué ataque engana a usuarios creando un punto de acceso inalambrico malicioso parecido a uno legitimo?",
     ["Evil twin", "Replay", "Smurf", "Birthday attack"],
     ["Evil twin", "Repeticion", "Smurf", "Ataque de cumpleaños"], 0,
     "An evil twin access point impersonates a trusted wireless network.",
     "Un punto evil twin suplanta una red inalambrica confiable."),
    ("module_1", 2, "Threats, Vulnerabilities, and Mitigations", "Amenazas, vulnerabilidades y mitigaciones",
     "Which vulnerability occurs when an application exposes more data than necessary through an API?",
     "¿Qué vulnerabilidad ocurre cuando una aplicacion expone mas datos de los necesarios por una API?",
     ["Excessive data exposure", "SQL deadlock", "Key stretching", "RAID mismatch"],
     ["Exposicion excesiva de datos", "SQL deadlock", "Key stretching", "Desajuste RAID"], 0,
     "APIs should return only the data required by the client and authorization context.",
     "Las APIs deben devolver solo los datos necesarios segun el cliente y la autorizacion."),
    ("module_1", 3, "Identity and Access", "Identidad y acceso",
     "Which approach adapts access decisions using context such as location, device health, and risk?",
     "¿Qué enfoque adapta decisiones de acceso usando contexto como ubicacion, salud del dispositivo y riesgo?",
     ["Context-aware access", "Static routing", "Open relay", "Disk striping"],
     ["Acceso consciente del contexto", "Enrutamiento estatico", "Open relay", "Striping de disco"], 0,
     "Context-aware access evaluates environmental and behavioral signals.",
     "El acceso contextual evalua senales ambientales y de comportamiento."),
    ("module_2", 4, "Security Architecture", "Arquitectura de seguridad",
     "Which zero trust idea removes automatic trust from internal networks?",
     "¿Qué idea de zero trust elimina la confianza automatica en redes internas?",
     ["Never trust, always verify", "Trust but verify annually", "Permit all internal traffic", "Use passwords only"],
     ["Nunca confiar, siempre verificar", "Confiar pero verificar anualmente", "Permitir todo trafico interno", "Usar solo contrasenas"], 0,
     "Zero trust requires continuous verification rather than implicit trust.",
     "Zero trust requiere verificacion continua en lugar de confianza implicita."),
    ("module_2", 4, "Security Architecture", "Arquitectura de seguridad",
     "Which device can enforce whether endpoints meet policy before joining a network?",
     "¿Qué dispositivo o tecnologia puede exigir que endpoints cumplan politicas antes de entrar a la red?",
     ["NAC", "UPS", "KVM", "CDN"],
     ["NAC", "UPS", "KVM", "CDN"], 0,
     "Network Access Control can check posture before granting access.",
     "NAC puede revisar la postura del endpoint antes de conceder acceso."),
    ("module_2", 5, "Cryptography and PKI", "Criptografia y PKI",
     "Which cryptographic method uses the same key to encrypt and decrypt?",
     "¿Qué metodo criptografico usa la misma clave para cifrar y descifrar?",
     ["Symmetric encryption", "Asymmetric encryption", "Hashing", "Tokenization"],
     ["Cifrado simetrico", "Cifrado asimetrico", "Hashing", "Tokenizacion"], 0,
     "Symmetric encryption uses one shared secret key.",
     "El cifrado simetrico usa una clave secreta compartida."),
    ("module_2", 5, "Cryptography and PKI", "Criptografia y PKI",
     "Which technique replaces sensitive data with non-sensitive placeholders?",
     "¿Qué tecnica reemplaza datos sensibles por valores no sensibles?",
     ["Tokenization", "Salting", "Compression", "Packet filtering"],
     ["Tokenizacion", "Salting", "Compresion", "Filtrado de paquetes"], 0,
     "Tokenization substitutes sensitive values while preserving business workflows.",
     "La tokenizacion sustituye valores sensibles manteniendo flujos de negocio."),
    ("module_2", 6, "Security Operations", "Operaciones de seguridad",
     "Which response platform automates and coordinates incident response workflows?",
     "¿Qué plataforma automatiza y coordina flujos de respuesta a incidentes?",
     ["SOAR", "DHCP", "RAID", "BGP"],
     ["SOAR", "DHCP", "RAID", "BGP"], 0,
     "SOAR helps orchestrate and automate response actions.",
     "SOAR ayuda a orquestar y automatizar acciones de respuesta."),
    ("module_2", 6, "Security Operations", "Operaciones de seguridad",
     "Which backup metric defines the maximum acceptable amount of data loss measured in time?",
     "¿Qué metrica de respaldo define la maxima perdida aceptable de datos medida en tiempo?",
     ["RPO", "RTO", "MTBF", "MTTR"],
     ["RPO", "RTO", "MTBF", "MTTR"], 0,
     "Recovery Point Objective defines how much data loss is acceptable.",
     "RPO define cuanta perdida de datos es aceptable."),
    ("module_3", 7, "Security Program Management", "Gestion del programa de seguridad",
     "Which agreement commonly defines uptime and support expectations with a provider?",
     "¿Qué acuerdo define comunmente disponibilidad y expectativas de soporte con un proveedor?",
     ["SLA", "CSR", "CRL", "MOU"],
     ["SLA", "CSR", "CRL", "MOU"], 0,
     "A service level agreement documents expected service performance.",
     "Un SLA documenta el rendimiento esperado del servicio."),
    ("module_3", 8, "Governance, Risk, and Compliance", "Gobernanza, riesgo y cumplimiento",
     "Which privacy role determines why and how personal data is processed?",
     "¿Qué rol de privacidad determina por qué y cómo se procesan datos personales?",
     ["Controller", "Processor", "Custodian", "Auditor"],
     ["Controlador", "Procesador", "Custodio", "Auditor"], 0,
     "A controller determines the purpose and means of processing personal data.",
     "Un controlador determina el proposito y los medios del procesamiento de datos personales."),
    ("module_3", 9, "Security Awareness", "Concientizacion de seguridad",
     "Which practice helps remote workers protect traffic on untrusted networks?",
     "¿Qué practica ayuda a trabajadores remotos a proteger trafico en redes no confiables?",
     ["Use a VPN or secure access solution", "Disable endpoint protection", "Share credentials with family", "Use open Wi-Fi for admin tasks"],
     ["Usar VPN o solucion de acceso seguro", "Deshabilitar proteccion endpoint", "Compartir credenciales con la familia", "Usar Wi-Fi abierto para tareas admin"], 0,
     "Secure remote access reduces exposure on untrusted networks.",
     "El acceso remoto seguro reduce exposicion en redes no confiables."),
]


def build_question(item, language):
    category, block_id, block_en, block_es, q_en, q_es, opts_en, opts_es, correct, exp_en, exp_es = item
    block_name = block_en if language == "en" else block_es
    question = q_en if language == "en" else q_es
    options = opts_en if language == "en" else opts_es
    explanation = exp_en if language == "en" else exp_es
    index = QUESTIONS.index(item) + 1
    difficulty = "beginner" if index % 5 == 0 else "intermediate" if index % 3 else "advanced"

    return {
        "id": f"security-701-{index:03d}",
        "category": category,
        "block_id": block_id,
        "block_name": block_name,
        "difficulty": difficulty,
        "tags": ["comptia", "security+", "sy0-701", category],
        "question": question,
        "options": options,
        "correct_answer": correct,
        "correct_answers": [correct],
        "explanation": explanation,
    }


payload = {
    "en": [build_question(item, "en") for item in QUESTIONS],
    "es": [build_question(item, "es") for item in QUESTIONS],
}

OUT_JSON.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(f"Wrote {OUT_JSON}")
print(f"English questions: {len(payload['en'])}")
print(f"Spanish questions: {len(payload['es'])}")
